# Generated by Django 4.2 on 2023-06-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clique',
            field=models.PositiveIntegerField(default=0, verbose_name='Cliques'),
        ),
    ]
