# Generated by Django 4.2 on 2023-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_clique'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='visualizacao',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualização'),
        ),
    ]
